#!/usr/bin/env bash
# takes domain and subdomain parameters and displays info for the specific subdomain

display_subdomain_info () {
    line=$(dig "${2}"."${1}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
        echo "${2} ${line}" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
        

if ["$#"-eq 1 ]
then
  display_subdomain_info "$1" "www"
  display_subdomain_info "$1" "lb-01"
  display_subdomain_info "$1" "web-01"
  display_subdomain_info "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  display_subdomain_info "$1" "$2"
fi
