#!/usr/bin/env bash
# Install nginx which should be listening to port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello, world!" | sudo kay /var/www/html/index.html
sudo service nginx restart
