#!/usr/bin/env bash
#configure nginx server to redirect_me
# the redirection is a 301 moved permanently

sudo apt-get upate
sudo apt-get install -y nginx
mkdir /etc/nginx/html
echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.html;
	location / redirect_me {
		return 301 https://WinnyKay3.github.io/profile/;
	}
}" > /etc/nginx/sites-enabled/default
sudo service nginx restart
