#!/usr/bin/env bash
# Install nginx which should be listening to port 80

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
