#!/usr/bin/env bash
#Displays "To infinity and beyond" indefinately
#with a sleep 2 in betwn each iteration
#Displays 'I am invincible!!!' when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
